
import type { Sale, Purchase, Expense, InventoryItem, StockMovement, AirtimeTransaction, MobileMoneyTransaction } from './types';

export const mockSales: Sale[] = [
  {
    id: 'SALE001',
    type: 'sale',
    description: 'Vente au détail - RUSH (Bouteille) 0,5L',
    amount: 250,
    date: '2024-07-26T10:30:00Z',
    category: 'Vente',
    client: 'Client Comptant',
    product: 'RUSH (Bouteille) 0,5L',
    reference: 'BO-ENE001',
    price: 250,
    quantity: 1,
    itemType: 'Boisson'
  },
  {
    id: 'SALE002',
    type: 'sale',
    description: 'Vente au détail - Okeola Pure Water (Unité)',
    amount: 50,
    date: '2024-07-26T10:32:00Z',
    category: 'Vente',
    client: 'Client Comptant',
    product: 'Okeola Pure Water (Unité)',
    reference: 'BO-EAU0016',
    price: 25,
    quantity: 2,
    itemType: 'Boisson'
  },
  {
    id: 'SALE003',
    type: 'sale',
    description: 'Vente au détail - Tamarin (Bouteille) 0,5L',
    amount: 200,
    date: '2024-07-26T10:35:00Z',
    category: 'Vente',
    client: 'Client Comptant',
    product: 'Tamarin (Bouteille) 0,5L',
    reference: 'BO-SUC001',
    price: 200,
    quantity: 1,
    itemType: 'Boisson'
  },
  {
    id: 'SALE004',
    type: 'sale',
    description: 'Vente au détail - Okeola Pure Water (Sachet)',
    amount: 25,
    date: '2024-07-26T10:38:00Z',
    category: 'Vente',
    client: 'Client Comptant',
    product: 'Okeola Pure Water (Sachet)',
    reference: 'BO-EAU0015',
    price: 25,
    quantity: 1,
    itemType: 'Boisson'
  },
  {
    id: 'SALE005',
    type: 'sale',
    description: 'Vente au détail - Okeola Pure Water (Sachet)',
    amount: 50,
    date: '2024-07-26T10:40:00Z',
    category: 'Vente',
    client: 'Client Comptant',
    product: 'Okeola Pure Water (Sachet)',
    reference: 'BO-EAU0015',
    price: 25,
    quantity: 2,
    itemType: 'Boisson'
  },
  {
    id: 'SALE006',
    type: 'sale',
    description: 'Vente au détail - RUSH (Bouteille) 0,5L',
    amount: 250,
    date: '2024-07-26T10:42:00Z',
    category: 'Vente',
    client: 'Client Comptant',
    product: 'RUSH (Bouteille) 0,5L',
    reference: 'BO-ENE001',
    price: 250,
    quantity: 1,
    itemType: 'Boisson'
  },
  {
    id: 'SALE007',
    type: 'sale',
    description: 'Vente au détail - Okeola Pure Water (Sachet)',
    amount: 25,
    date: '2024-07-26T10:45:00Z',
    category: 'Vente',
    client: 'Client Comptant',
    product: 'Okeola Pure Water (Sachet)',
    reference: 'BO-EAU0015',
    price: 25,
    quantity: 1,
    itemType: 'Boisson'
  },
  {
    id: 'SALE008',
    type: 'sale',
    description: 'Vente au détail - RUSH (Bouteille) 0,5L',
    amount: 250,
    date: '2024-07-26T10:48:00Z',
    category: 'Vente',
    client: 'Client Comptant',
    product: 'RUSH (Bouteille) 0,5L',
    reference: 'BO-ENE001',
    price: 250,
    quantity: 1,
    itemType: 'Boisson'
  },
  {
    id: 'SALE009',
    type: 'sale',
    description: 'Vente au détail - Ampoule 1W OLEDN',
    amount: 1125,
    date: '2024-07-26T10:50:00Z',
    category: 'Vente',
    client: 'Client Comptant',
    product: 'T100 Ampoule 1W OLEDN',
    reference: 'EL-AMP0030',
    price: 1125,
    quantity: 1,
    itemType: 'Électronique'
  },
  {
    id: 'SALE010',
    type: 'sale',
    description: "Vente au détail - Boisson U",
    amount: 400,
    date: '2024-07-26T10:52:00Z',
    category: 'Vente',
    client: 'Client Comptant',
    product: "Boisson U",
    reference: "BO-SUC0020",
    price: 400,
    quantity: 1,
    itemType: 'Boisson'
  },
  {
    id: 'SALE011',
    type: 'sale',
    description: "Vente au détail - LAIT UHT NATUREL",
    amount: 875,
    date: '2024-07-26T10:55:00Z',
    category: 'Vente',
    client: 'Client Comptant',
    product: "LAIT UHT NATUREL",
    reference: "PRODLAI0030",
    price: 875,
    quantity: 1,
    itemType: 'Produits laitiers'
  },
  {
    id: 'SALE012',
    type: 'sale',
    description: "Vente au détail - Assortiment",
    amount: 125,
    date: '2024-07-26T10:58:00Z',
    category: 'Vente',
    client: 'Client Comptant',
    product: "Assortiment",
    reference: "CONFISER0020",
    price: 125,
    quantity: 1,
    itemType: 'Confiserie'
  }
];

export const mockPurchases: Purchase[] = [
  {
    id: 'PUR001',
    type: 'purchase',
    description: 'Commande Fournisseur Z',
    amount: 80000,
    date: '2024-05-15T09:00:00Z',
    category: 'Achat',
    supplier: 'Fournisseur Z',
    product: 'Matière première A',
  },
];

export const mockExpenses: Expense[] = [
  {
    id: 'EXP001',
    type: 'expense',
    description: 'Facture électricité - Mai 2024',
    amount: 25075,
    date: '2024-05-22T11:00:00Z',
    category: 'Utilitaires',
    currency: 'F',
    tags: ['électricité', 'mai'],
  },
  {
    id: 'EXP002',
    type: 'expense',
    description: 'Salaires - Mai 2024',
    amount: 1500000,
    date: '2024-05-25T16:00:00Z',
    category: 'Salaires',
    currency: 'F',
    tags: ['salaires'],
  },
  {
    id: 'EXP003',
    type: 'expense',
    description: 'Transport de marchandises',
    amount: 35000,
    date: '2024-05-18T12:00:00Z',
    category: 'Transport',
    currency: 'F',
    tags: ['logistique'],
  },
];

export const mockInventory: InventoryItem[] = [
  {
    "id": "1",
    "productName": "RUSH (Bouteille) 0,5L",
    "sku": "BO-ENE001",
    "category": "Boisson",
    "brand": "RUSH",
    "reference": "BO-ENE001",
    "inStock": 100,
    "inTransit": 50,
    "reorderLevel": 20,
    "supplier": "Fournisseur A",
    "defaultPrice": 250,
    "costPrice": 200,
    "isQuickSale": true
  },
  {
    "id": "2",
    "productName": "Okeola Pure Water (Unité)",
    "sku": "BO-EAU0016",
    "category": "Boisson",
    "brand": "Okeola",
    "reference": "BO-EAU0016",
    "inStock": 500,
    "inTransit": 0,
    "reorderLevel": 100,
    "supplier": "Fournisseur B",
    "defaultPrice": 50,
    "costPrice": 20,
    "isQuickSale": true
  },
  {
    "id": "3",
    "productName": "Tamarin (Bouteille) 0,5L",
    "sku": "BO-SUC001",
    "category": "Boisson",
    "brand": "Tamarin",
    "reference": "BO-SUC001",
    "inStock": 80,
    "inTransit": 20,
    "reorderLevel": 15,
    "supplier": "Fournisseur A",
    "defaultPrice": 200,
    "costPrice": 150,
    "isQuickSale": true
  },
  {
    "id": "4",
    "productName": "Okeola Pure Water (Sachet)",
    "sku": "BO-EAU0015",
    "category": "Boisson",
    "brand": "Okeola",
    "reference": "BO-EAU0015",
    "inStock": 1000,
    "inTransit": 200,
    "reorderLevel": 200,
    "supplier": "Fournisseur B",
    "defaultPrice": 25,
    "costPrice": 10,
    "isQuickSale": true
  },
  {
    "id": "5",
    "productName": "T100 Ampoule 1W OLEDN",
    "sku": "EL-AMP0030",
    "category": "Électronique",
    "brand": "OLEDN",
    "reference": "EL-AMP0030",
    "inStock": 30,
    "inTransit": 10,
    "reorderLevel": 5,
    "supplier": "Fournisseur C",
    "costPrice": 900,
  },
  {
    "id": "6",
    "productName": "Boisson U",
    "sku": "BO-SUC0020",
    "category": "Boisson",
    "brand": "U",
    "reference": "BO-SUC0020",
    "inStock": 120,
    "inTransit": 0,
    "reorderLevel": 25,
    "supplier": "Fournisseur A",
    "defaultPrice": 400,
    "costPrice": 320,
  },
  {
    "id": "7",
    "productName": "LAIT UHT NATUREL",
    "sku": "PRODLAI0030",
    "category": "Produits laitiers",
    "brand": "Laitière du Berger",
    "reference": "PRODLAI0030",
    "inStock": 60,
    "inTransit": 30,
    "reorderLevel": 10,
    "supplier": "Fournisseur D",
    "defaultPrice": 875,
    "costPrice": 750
  },
  {
    "id": "8",
    "productName": "Assortiment",
    "sku": "CONFISER0020",
    "category": "Confiserie",
    "brand": "Divers",
    "reference": "CONFISER0020",
    "inStock": 200,
    "inTransit": 0,
    "reorderLevel": 50,
    "supplier": "Fournisseur E",
    "defaultPrice": 125,
    "costPrice": 80,
  }
];

export const mockStockMovements: StockMovement[] = [
    { id: 'MOV001', productId: 'PROD001', type: 'in', quantity: 50, date: '2024-05-28T10:00:00Z', reason: 'Livraison Fournisseur' },
    { id: 'MOV002', productId: 'PROD002', type: 'out', quantity: 24, date: '2024-05-28T11:30:00Z', reason: 'Vente' },
    { id: 'MOV003', productId: 'PROD003', type: 'out', quantity: 10, date: '2024-05-28T12:00:00Z', reason: 'Vente' },
    { id: 'MOV004', productId: 'PROD004', type: 'adjustment', quantity: -2, date: '2024-05-28T14:00:00Z', reason: 'Perte / Casse' },
    { id: 'MOV005', productId: 'PROD001', type: 'out', quantity: 15, date: '2024-05-28T15:00:00Z', reason: 'Vente' },
];

export const mockAirtimeTransactions: AirtimeTransaction[] = [
    { id: 'AIR001', type: 'purchase', provider: 'Moov', amount: 1000000, commission: 0, date: '2024-05-29T09:00:00Z' },
    { id: 'AIR002', type: 'sale', provider: 'Moov', amount: 5000, commission: 250, date: '2024-05-29T09:15:00Z' },
    { id: 'AIR003', type: 'sale', provider: 'Yas', amount: 10000, commission: 500, date: '2024-05-29T09:30:00Z' },
    { id: 'AIR004', type: 'purchase', provider: 'Yas', amount: 500000, commission: 0, date: '2024-05-29T10:00:00Z' },
    { id: 'AIR005', type: 'sale', provider: 'Moov', amount: 2000, commission: 100, date: '2024-05-29T10:15:00Z' },
];

export const mockMobileMoneyTransactions: MobileMoneyTransaction[] = [
    { id: 'MM001', transactionId: 'MM-DEP-001', type: 'deposit', provider: 'Mixx', amount: 50000, commission: 250, date: '2024-05-29T11:00:00Z' },
    { id: 'MM002', transactionId: 'MM-WDR-001', type: 'withdrawal', provider: 'Flooz', amount: 25000, commission: 150, date: '2024-05-29T11:30:00Z' },
    { id: 'MM003', transactionId: 'MM-DEP-002', type: 'deposit', provider: 'Mixx', amount: 100000, commission: 500, date: '2024-05-29T12:00:00Z' },
    { id: 'MM004', transactionId: 'MM-WDR-002', type: 'withdrawal', provider: 'Flooz', amount: 30000, commission: 200, date: '2024-05-29T12:30:00Z' },
];
